[project]
name = "xmltodict_server"
version = "0.1.0"
description = "MCP Server for xmltodict_server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp",
    "pydantic",
    "python-dotenv",
    "structlog",
    "wrapt",
    "xmltodict",
]

[tool.uv]
dev-dependencies = []
