[project]
name = "academic_server"
version = "0.1.0"
description = "MCP Server for academic_server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx",
    "mcp",
    "pydantic",
    "python-dotenv",
    "structlog",
    "wrapt",
]

[tool.uv]
dev-dependencies = []
