[project]
name = "scraper_server"
version = "0.1.0"
description = "MCP Server for scraper_server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "#   mcp",
    "#   structlog",
    "mcp"
]

[tool.uv]
dev-dependencies = []
