[project]
name = "sec_edgar_server"
version = "0.1.0"
description = "MCP Server for SEC Edgar"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4",
    "httpx",
    "lxml",
    "mcp",
    "pandas",
    "pydantic",
    "python-dotenv",
    "sec-edgar-downloader",
    "structlog",
    "textblob",
    "wrapt",
]

[tool.uv]
dev-dependencies = []
