[project]
name = "numpy_server"
version = "0.1.0"
description = "MCP Server for Numpy"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=0.1.0",
    "numpy",
    "pandas",
    "structlog"
]

[tool.uv]
dev-dependencies = []
