[project]
name = "visualization_server"
version = "0.1.0"
description = "MCP Server for visualization_server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp",
    "numpy",
    "pandas",
    "plotly",
    "pydantic",
    "python-dotenv",
    "structlog",
    "wrapt",
]

[tool.uv]
dev-dependencies = []
