[project]
name = "sklearn_server"
version = "0.1.0"
description = "MCP Server for sklearn_server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "joblib",
    "mcp",
    "numpy",
    "pandas",
    "pydantic",
    "python-dotenv",
    "scikit-learn",
    "scipy",
    "structlog",
    "threadpoolctl",
    "wrapt",
]

[tool.uv]
dev-dependencies = []
