[project]
name = "web3_server"
version = "0.1.0"
description = "MCP Server for web3_server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "#   mcp",
    "#   structlog",
    "#   web3",
    "mcp"
]

[tool.uv]
dev-dependencies = []
