[project]
name = "web3_server"
version = "0.1.0"
description = "MCP Server for web3_server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "eth-abi",
    "mcp",
    "pydantic",
    "python-dotenv",
    "structlog",
    "web3",
    "wrapt",
]

[tool.uv]
dev-dependencies = []
