[project]
name = "bs4_server"
version = "0.1.0"
description = "MCP Server for bs4_server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "#   mcp",
    "#   beautifulsoup4",
    "#   lxml",
    "#   html5lib",
    "#   structlog",
    "mcp"
]

[tool.uv]
dev-dependencies = []
