[project]
name = "tradingview_server"
version = "0.1.0"
description = "MCP Server for tradingview_server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "#   mcp",
    "#   requests",
    "#   structlog",
    "#   tradingview_ta",
    "mcp"
]

[tool.uv]
dev-dependencies = []
